"""Added display_name to user

Revision ID: 333de03d19f4
Revises: 39e11d2ccf61
Create Date: 2013-10-05 16:05:32.235458

"""

# revision identifiers, used by Alembic.
revision = '333de03d19f4'
down_revision = '39e11d2ccf61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    ### end Alembic commands ###
