"""Added publication flag

Revision ID: 4bb3aad78900
Revises: 333de03d19f4
Create Date: 2013-12-06 20:09:24.649815

"""

# revision identifiers, used by Alembic.
revision = '4bb3aad78900'
down_revision = '333de03d19f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=False, server_default='TRUE'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    ### end Alembic commands ###
